In [29]:
# https://assets.datacamp.com/production/repositories/5981/datasets/8582db71ec282f17c504c8eb794d54758fd8d5d8/telecom_churn_clean.csv

In [30]:
import pandas as pd
import numpy as np

In [31]:
#Загружаем датасет
df = pd.read_csv(r'D:\PycharmProjects\urfu_mlops\back_dataset\telecom_churn_clean.csv')
df = df.drop(df.columns[0], axis=1)
df.sample(10)

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn
2864,153,415,0,0,0,228.9,102,38.91,160.7,136,13.66,203.1,109,9.14,12.5,2,3.38,0,0
211,144,510,1,0,0,203.5,100,34.60,247.6,103,21.05,194.3,94,8.74,11.9,11,3.21,0,0
1491,89,408,0,0,0,197.1,110,33.51,165.9,115,14.10,227.3,106,10.23,12.8,3,3.46,1,0
1588,115,415,1,0,0,180.0,119,30.60,198.8,126,16.90,217.1,70,9.77,12.4,3,3.35,1,0
1562,37,415,0,0,0,191.1,69,32.49,129.2,113,10.98,207.5,117,9.34,12.9,1,3.48,0,0
364,194,408,0,0,0,162.3,88,27.59,213.7,118,18.16,192.1,81,8.64,10.9,2,2.94,0,0
170,68,408,0,0,0,237.1,105,40.31,223.5,105,19.00,97.4,79,4.38,13.2,2,3.56,1,0
1754,54,415,1,0,0,190.5,108,32.39,259.7,108,22.07,141.5,111,6.37,9.7,2,2.62,2,1
221,127,408,0,1,22,166.0,114,28.22,174.5,103,14.83,244.9,68,11.02,10.2,6,2.75,1,0
915,152,408,0,0,0,101.2,122,17.20,141.6,87,12.04,198.5,124,8.93,7.5,3,2.03,2,0

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   account_length          3333 non-null   int64
 1   area_code               3333 non-null   int64
 2   international_plan      3333 non-null   int64
 3   voice_mail_plan         3333 non-null   int64
 4   number_vmail_messages   3333 non-null   int64
 5   total_day_minutes       3333 non-null   float64
 6   total_day_calls         3333 non-null   int64
 7   total_day_charge        3333 non-null   float64
 8   total_eve_minutes       3333 non-null   float64
 9   total_eve_calls         3333 non-null   int64
 10  total_eve_charge        3333 non-null   float64
 11  total_night_minutes     3333 non-null   float64
 12  total_night_calls       3333 non-null   int64
 13  total_night_charge      3333 non-null   float64
 14  total_intl_minutes      3333 non-null   float64
 15  total_intl_calls        3333 non-null   int64
 16  total_intl_charge       3333 non-null   float64
 17  customer_service_calls  3333 non-null   int64
 18  churn                   3333 non-null   int64
dtypes: float64(8), int64(11)
memory usage: 494.9 KB

In [33]:
df.nunique()

account_length             212
area_code                    3
international_plan           2
voice_mail_plan              2
number_vmail_messages       46
total_day_minutes         1667
total_day_calls            119
total_day_charge          1667
total_eve_minutes         1611
total_eve_calls            123
total_eve_charge          1440
total_night_minutes       1591
total_night_calls          120
total_night_charge         933
total_intl_minutes         162
total_intl_calls            21
total_intl_charge          162
customer_service_calls      10
churn                        2
dtype: int64

In [34]:
# from sklearn.model_selection import train_test_split

# X = df.drop(['churn'], axis=1)
# y = df['churn']

# random_id = 123
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=random_id)

In [35]:
from pathlib import Path
import pandas as pd

# Расположения
base_path = Path.cwd()
train_folder_name = 'train'
test_folder_name = 'test'
train_folder_path = base_path / train_folder_name
test_folder_path = base_path / test_folder_name

#
X_train = pd.read_csv(train_folder_path / 'X_train.csv')
y_train = pd.read_csv(train_folder_path / 'y_train.csv')
X_test = pd.read_csv(test_folder_path / 'X_test.csv')
y_test = pd.read_csv(test_folder_path / 'y_test.csv')

X_train.head(5)

,Unnamed: 0,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls
0,1402,70,415,0,0,0,213.4,86,36.28,204.7,77,17.40,256.6,101,11.55,5.7,4,1.54,1
1,1855,67,510,0,0,0,109.1,134,18.55,142.3,76,12.10,91.2,86,4.10,10.9,5,2.94,2
2,633,122,415,0,1,34,146.4,104,24.89,89.7,103,7.62,220.0,91,9.90,15.6,4,4.21,2
3,1483,107,510,1,0,0,234.1,91,39.80,163.1,105,13.86,282.5,100,12.71,10.0,3,2.70,1
4,2638,105,510,0,0,0,125.4,116,21.32,261.5,95,22.23,241.6,104,10.87,11.4,9,3.08,2

In [36]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# import matplotlib.pyplot as plt

In [37]:
df = pd.read_csv(base_path.parent / 'back_dataset' / 'telecom_churn_clean.csv')
df = df.drop(df.columns[0], axis=1)
df.head()

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn
0,128,415,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

In [38]:
df.nunique()

account_length             212
area_code                    3
international_plan           2
voice_mail_plan              2
number_vmail_messages       46
total_day_minutes         1667
total_day_calls            119
total_day_charge          1667
total_eve_minutes         1611
total_eve_calls            123
total_eve_charge          1440
total_night_minutes       1591
total_night_calls          120
total_night_charge         933
total_intl_minutes         162
total_intl_calls            21
total_intl_charge          162
customer_service_calls      10
churn                        2
dtype: int64

In [39]:
# plt.pie(y.value_counts(), labels=['no', 'yes'])
# plt.title("Распределение целевой переменной")

In [40]:

X = df.drop(['churn'], axis=1)
y = df['churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=123
)

In [41]:
import time
from sklearn import svm

start_time = time.perf_counter()

clf1 = svm.SVC(kernel='linear', C=1, random_state=123)
clf1.fit(X_train, y_train)

end_time = time.perf_counter()
training_time = end_time - start_time
print(f"Время обучения: {training_time:.2f} секунд")
print(f"accuracy: {clf1.score(X_test, y_test)}")

Время обучения: 30.46 секунд
accuracy: 0.868

In [42]:
from sklearn.model_selection import cross_val_score

start_time = time.perf_counter()

clf2 = svm.SVC(kernel='linear', C=1, random_state=123)
scores = cross_val_score(clf2, X, y, cv=5)

end_time = time.perf_counter()
training_time = end_time - start_time
print(f"Время обучения: {training_time:.2f} секунд")
print(f"accuracy: {scores}")

Время обучения: 176.30 секунд
accuracy: [0.85757121 0.85757121 0.85757121 0.85585586 0.85885886]

In [43]:

from sklearn import preprocessing

scaler = preprocessing.StandardScaler().set_output(transform="pandas")
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled.head()

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls
1402,-0.767893,-0.509593,-0.328310,-0.613515,-0.587624,0.618769,-0.721211,0.618927,0.069871,-1.156734,0.069926,1.088667,0.052115,1.089926,-1.645501,-0.200722,-1.644994,-0.415269
1855,-0.843585,1.760678,-0.328310,-0.613515,-0.587624,-1.293778,1.655252,-1.293517,-1.167277,-1.207278,-1.166291,-2.162302,-0.720990,-2.164029,0.227019,0.198158,0.222249,0.337507
633,0.544113,-0.509593,-0.328310,1.629951,1.900976,-0.609809,0.169963,-0.609654,-2.210130,0.157417,-2.211244,0.369287,-0.463288,0.369252,1.919489,-0.200722,1.916105,0.337507
1483,0.165650,1.760678,3.045904,-0.613515,-0.587624,0.998345,-0.473663,0.998611,-0.754894,0.258506,-0.755774,1.597736,0.000574,1.596582,-0.097071,-0.599603,-0.097850,-0.415269
2638,0.115188,1.760678,-0.328310,-0.613515,-0.587624,-0.994886,0.764078,-0.994731,1.195994,-0.246937,1.196515,0.793839,0.206736,0.792921,0.407069,1.793679,0.408973,0.337507

In [44]:

min_max_scaler = preprocessing.MinMaxScaler().set_output(transform="pandas")
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_test_minmax = min_max_scaler.transform(X_test)

X_train_minmax.head()

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls
1402,0.285124,0.068627,0.0,0.0,0.000000,0.608324,0.521212,0.608317,0.577922,0.458333,0.577881,0.658764,0.519084,0.658934,0.285,0.20,0.285185,0.111111
1855,0.272727,1.000000,0.0,0.0,0.000000,0.311003,0.812121,0.311033,0.401750,0.452381,0.401860,0.191928,0.404580,0.191850,0.545,0.25,0.544444,0.222222
633,0.500000,0.068627,0.0,1.0,0.666667,0.417332,0.630303,0.417337,0.253247,0.613095,0.253072,0.555461,0.442748,0.555486,0.780,0.20,0.779630,0.222222
1483,0.438017,1.000000,1.0,0.0,0.000000,0.667332,0.551515,0.667337,0.460474,0.625000,0.460312,0.731866,0.511450,0.731661,0.500,0.15,0.500000,0.111111
2638,0.429752,1.000000,0.0,0.0,0.000000,0.357469,0.703030,0.357478,0.738283,0.565476,0.738293,0.616427,0.541985,0.616301,0.570,0.45,0.570370,0.222222

In [45]:

start_time = time.perf_counter()

clf1 = svm.SVC(kernel='linear', C=1, random_state=123)
clf1.fit(X_train_scaled, y_train)

end_time = time.perf_counter()
training_time = end_time - start_time
print(f"Время обучения: {training_time:.2f} секунд")
print(f"accuracy: {clf1.score(X_test_scaled, y_test)}")


start_time = time.perf_counter()

clf2 = svm.SVC(kernel='linear', C=1, random_state=123)
scores = cross_val_score(clf2, scaler.transform(X), y, cv=5)

end_time = time.perf_counter()
training_time = end_time - start_time
print(f"Время обучения: {training_time:.2f} секунд")
print(f"accuracy: {scores}")
print(f"accuracy: {scores.mean()}")

Время обучения: 0.10 секунд
accuracy: 0.866
Время обучения: 1.35 секунд
accuracy: [0.85457271 0.85457271 0.85457271 0.85585586 0.85585586]
accuracy: 0.8550859705282494