In [1]:
# https://assets.datacamp.com/production/repositories/5981/datasets/8582db71ec282f17c504c8eb794d54758fd8d5d8/telecom_churn_clean.csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Загружаем датасет
df = pd.read_csv(r'D:\PycharmProjects\urfu_mlops\back_dataset\telecom_churn_clean.csv')
df = df.drop(df.columns[0], axis=1)
df.sample(10)

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn
2026,69,415,0,0,0,153.7,109,26.13,194.0,105,16.49,256.1,114,11.52,14.1,6,3.81,1,0
1354,105,408,0,0,0,147.7,103,25.11,222.7,78,18.93,163.5,102,7.36,12.8,3,3.46,2,0
810,123,510,0,0,0,194.0,118,32.98,242.0,114,20.57,146.3,108,6.58,12.1,4,3.27,1,0
653,87,415,0,1,22,263.8,65,44.85,103.4,115,8.79,208.1,109,9.36,8.5,3,2.30,3,0
136,75,415,0,1,21,175.8,97,29.89,217.5,106,18.49,237.5,134,10.69,5.3,4,1.43,5,0
638,13,415,0,1,31,265.3,94,45.10,147.6,95,12.55,259.3,117,11.67,12.9,1,3.48,1,0
36,36,408,0,1,30,146.3,128,24.87,162.5,80,13.81,129.3,109,5.82,14.5,6,3.92,0,0
2987,131,408,1,0,0,122.3,83,20.79,118.8,94,10.10,147.9,95,6.66,13.7,3,3.70,3,1
1574,122,415,1,1,40,216.4,80,36.79,249.7,90,21.22,185.9,99,8.37,12.7,4,3.43,1,0
1025,148,415,0,1,11,252.9,129,42.99,284.3,88,24.17,262.8,99,11.83,12.3,1,3.32,1,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   account_length          3333 non-null   int64
 1   area_code               3333 non-null   int64
 2   international_plan      3333 non-null   int64
 3   voice_mail_plan         3333 non-null   int64
 4   number_vmail_messages   3333 non-null   int64
 5   total_day_minutes       3333 non-null   float64
 6   total_day_calls         3333 non-null   int64
 7   total_day_charge        3333 non-null   float64
 8   total_eve_minutes       3333 non-null   float64
 9   total_eve_calls         3333 non-null   int64
 10  total_eve_charge        3333 non-null   float64
 11  total_night_minutes     3333 non-null   float64
 12  total_night_calls       3333 non-null   int64
 13  total_night_charge      3333 non-null   float64
 14  total_intl_minutes      3333 non-null   float64
 15  total_intl_calls        3333 non-null   int64
 16  total_intl_charge       3333 non-null   float64
 17  customer_service_calls  3333 non-null   int64
 18  churn                   3333 non-null   int64
dtypes: float64(8), int64(11)
memory usage: 494.9 KB

In [5]:
df.nunique()

account_length             212
area_code                    3
international_plan           2
voice_mail_plan              2
number_vmail_messages       46
total_day_minutes         1667
total_day_calls            119
total_day_charge          1667
total_eve_minutes         1611
total_eve_calls            123
total_eve_charge          1440
total_night_minutes       1591
total_night_calls          120
total_night_charge         933
total_intl_minutes         162
total_intl_calls            21
total_intl_charge          162
customer_service_calls      10
churn                        2
dtype: int64

In [6]:
# from sklearn.model_selection import train_test_split

# X = df.drop(['churn'], axis=1)
# y = df['churn']

# random_id = 123
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=random_id)

In [7]:
from pathlib import Path
import pandas as pd

# Расположения
base_path = Path.cwd()
train_folder_name = 'train'
test_folder_name = 'test'
train_folder_path = base_path / train_folder_name
test_folder_path = base_path / test_folder_name

#
X_train = pd.read_csv(train_folder_path / 'X_train.csv')
y_train = pd.read_csv(train_folder_path / 'y_train.csv')
X_test = pd.read_csv(test_folder_path / 'X_test.csv')
y_test = pd.read_csv(test_folder_path / 'y_test.csv')

X_train.head(5)

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls
0,-0.767893,-0.509593,-0.328310,-0.613515,-0.587624,0.618769,-0.721211,0.618927,0.069871,-1.156734,0.069926,1.088667,0.052115,1.089926,-1.645501,-0.200722,-1.644994,-0.415269
1,-0.843585,1.760678,-0.328310,-0.613515,-0.587624,-1.293778,1.655252,-1.293517,-1.167277,-1.207278,-1.166291,-2.162302,-0.720990,-2.164029,0.227019,0.198158,0.222249,0.337507
2,0.544113,-0.509593,-0.328310,1.629951,1.900976,-0.609809,0.169963,-0.609654,-2.210130,0.157417,-2.211244,0.369287,-0.463288,0.369252,1.919489,-0.200722,1.916105,0.337507
3,0.165650,1.760678,3.045904,-0.613515,-0.587624,0.998345,-0.473663,0.998611,-0.754894,0.258506,-0.755774,1.597736,0.000574,1.596582,-0.097071,-0.599603,-0.097850,-0.415269
4,0.115188,1.760678,-0.328310,-0.613515,-0.587624,-0.994886,0.764078,-0.994731,1.195994,-0.246937,1.196515,0.793839,0.206736,0.792921,0.407069,1.793679,0.408973,0.337507

In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv(base_path.parent / 'back_dataset' / 'telecom_churn_clean.csv')
df = df.drop(df.columns[0], axis=1)
df.head()

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn
0,128,415,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

In [10]:
df.nunique()

account_length             212
area_code                    3
international_plan           2
voice_mail_plan              2
number_vmail_messages       46
total_day_minutes         1667
total_day_calls            119
total_day_charge          1667
total_eve_minutes         1611
total_eve_calls            123
total_eve_charge          1440
total_night_minutes       1591
total_night_calls          120
total_night_charge         933
total_intl_minutes         162
total_intl_calls            21
total_intl_charge          162
customer_service_calls      10
churn                        2
dtype: int64

In [11]:
# plt.pie(y.value_counts(), labels=['no', 'yes'])
# plt.title("Распределение целевой переменной")

In [12]:

X = df.drop(['churn'], axis=1)
y = df['churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=123
)

In [ ]:
import time
from sklearn import svm

start_time = time.perf_counter()

clf1 = svm.SVC(kernel='linear', C=1, random_state=123)
clf1.fit(X_train, y_train)

end_time = time.perf_counter()
training_time = end_time - start_time
print(f"Время обучения: {training_time:.2f} секунд")
print(f"accuracy: {clf1.score(X_test, y_test)}")

Время обучения: 26.59 секунд
accuracy: 0.868

In [14]:
from sklearn.model_selection import cross_val_score

start_time = time.perf_counter()

clf2 = svm.SVC(kernel='linear', C=1, random_state=123)
scores = cross_val_score(clf2, X, y, cv=5)

end_time = time.perf_counter()
training_time = end_time - start_time
print(f"Время обучения: {training_time:.2f} секунд")
print(f"accuracy: {scores}")

Время обучения: 176.63 секунд
accuracy: [0.85757121 0.85757121 0.85757121 0.85585586 0.85885886]

In [15]:

from sklearn import preprocessing

scaler = preprocessing.StandardScaler().set_output(transform="pandas")
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled.head()

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls
1402,-0.767893,-0.509593,-0.328310,-0.613515,-0.587624,0.618769,-0.721211,0.618927,0.069871,-1.156734,0.069926,1.088667,0.052115,1.089926,-1.645501,-0.200722,-1.644994,-0.415269
1855,-0.843585,1.760678,-0.328310,-0.613515,-0.587624,-1.293778,1.655252,-1.293517,-1.167277,-1.207278,-1.166291,-2.162302,-0.720990,-2.164029,0.227019,0.198158,0.222249,0.337507
633,0.544113,-0.509593,-0.328310,1.629951,1.900976,-0.609809,0.169963,-0.609654,-2.210130,0.157417,-2.211244,0.369287,-0.463288,0.369252,1.919489,-0.200722,1.916105,0.337507
1483,0.165650,1.760678,3.045904,-0.613515,-0.587624,0.998345,-0.473663,0.998611,-0.754894,0.258506,-0.755774,1.597736,0.000574,1.596582,-0.097071,-0.599603,-0.097850,-0.415269
2638,0.115188,1.760678,-0.328310,-0.613515,-0.587624,-0.994886,0.764078,-0.994731,1.195994,-0.246937,1.196515,0.793839,0.206736,0.792921,0.407069,1.793679,0.408973,0.337507

In [16]:

min_max_scaler = preprocessing.MinMaxScaler().set_output(transform="pandas")
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_test_minmax = min_max_scaler.transform(X_test)

X_train_minmax.head()

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls
1402,0.285124,0.068627,0.0,0.0,0.000000,0.608324,0.521212,0.608317,0.577922,0.458333,0.577881,0.658764,0.519084,0.658934,0.285,0.20,0.285185,0.111111
1855,0.272727,1.000000,0.0,0.0,0.000000,0.311003,0.812121,0.311033,0.401750,0.452381,0.401860,0.191928,0.404580,0.191850,0.545,0.25,0.544444,0.222222
633,0.500000,0.068627,0.0,1.0,0.666667,0.417332,0.630303,0.417337,0.253247,0.613095,0.253072,0.555461,0.442748,0.555486,0.780,0.20,0.779630,0.222222
1483,0.438017,1.000000,1.0,0.0,0.000000,0.667332,0.551515,0.667337,0.460474,0.625000,0.460312,0.731866,0.511450,0.731661,0.500,0.15,0.500000,0.111111
2638,0.429752,1.000000,0.0,0.0,0.000000,0.357469,0.703030,0.357478,0.738283,0.565476,0.738293,0.616427,0.541985,0.616301,0.570,0.45,0.570370,0.222222

In [ ]:

start_time = time.perf_counter()

clf1 = svm.SVC(kernel='linear', C=20, random_state=123)
clf1.fit(X_train_scaled, y_train)

end_time = time.perf_counter()
training_time = end_time - start_time
print(f"Время обучения: {training_time:.2f} секунд")
print(f"accuracy: {clf1.score(X_test_scaled, y_test)}")

y_pred = clf1.predict(X_test_scaled)
from sklearn.metrics import precision_score, recall_score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

print(np.unique(y_pred))

# start_time = time.perf_counter()

# clf2 = svm.SVC(kernel='linear', C=1, random_state=123)
# scores = cross_val_score(clf2, scaler.transform(X), y, cv=5)

# end_time = time.perf_counter()
# training_time = end_time - start_time
# print(f"Время обучения: {training_time:.2f} секунд")
# print(f"accuracy: {scores}")
# print(f"accuracy: {scores.mean()}")

# y_pred = cross_val_score.predict(X_test_scaled)
# print(np.unique(y_pred))

:

: